name: Build and deploy ASP.Net Core app to Azure Web App - gimnasio-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      contents: read   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Publish app
        run: dotnet publish -c Release -o ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_70AE633E661B47ABB16C8FAC2772B497 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FE053B12D23C4A759B0F70FE506C4D96 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_250A1F70F4D745A7A4012DB04F54E716 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gimnasio-api'
          slot-name: 'Production'
          package: ./publish
